stages:
  download_extract_zip:
    cmd: curl -L "https://www.dropbox.com/s/if42duiggv5am29/diplomacy-v1-27k-msgs.zip?dl=1"
      -o raw.zip && mkdir -p data/raw && unzip raw.zip -d data/raw/ && rm raw.zip
    outs:
    - data/raw/other_maps.jsonl:
        cache: false
    - data/raw/standard_no_press.jsonl:
        cache: false
    - data/raw/standard_press_with_msgs.jsonl:
        cache: false
    - data/raw/standard_press_without_msgs.jsonl:
        cache: false
    - data/raw/standard_public_press.jsonl:
        cache: false 
